INSERT INTO Ramos (nombre, semestre, descripcion, color) VALUES
('T1 + T2 Orden y Espacio', 1, 'T1 + T2 Orden y Espacio', '#dcdee0'),
('Historia del Urbanismo', 1, 'Historia del Urbanismo', '#f4b7a5'),
('Arquitectura Clásica', 1, 'Arquitectura Clásica', '#ce8c7c'),
('Ciencias para la Arquitectura', 1, 'Ciencias para la Arquitectura', '#d36e54'),
('Visualización y Materia', 1, 'Visualización y Materia', '#b17076'),
('T1 + T2 Orden y Espacio', 2, 'T1 + T2 Orden y Espacio', '#dcdee0'),
('Análisis Estructural', 2, 'Análisis Estructural', '#d36e54'),
('Procesos Constructivos Macizos', 2, 'Procesos Constructivos Macizos', '#d36e54'),
('Diseño Asistido por Computador', 2, 'Diseño Asistido por Computador', '#b17076'),
('Inglés General I', 2, 'Inglés General I', '#dfccc5'),
('Taller 3 Habitar y Lugar', 3, 'Taller 3 Habitar y Lugar', '#dcdee0'),
('Workshop Latitud Sur. Convalida por taller 3, 4 ó 5.', 3, 'Workshop Latitud Sur. Convalida por taller 3, 4 ó 5.', '#e5bc7d'),
('Paisaje y Lugar', 3, 'Paisaje y Lugar', '#a7b2b7'),
('Teoría del Urbanismo', 3, 'Teoría del Urbanismo', '#f4b7a5'),
('Arquitectura Moderna', 3, 'Arquitectura Moderna', '#ce8c7c'),
('Seminario de Extensión 1', 3, 'Seminario de Extensión 1', '#e5bc7d'),
('Inglés General II', 3, 'Inglés General II', '#dfccc5'),
('Workshop Latitud Sur. Convalida por taller 3, 4 ó 5.', 4, 'Workshop Latitud Sur. Convalida por taller 3, 4 ó 5.', '#e5bc7d'),
('Taller 4 Habitar y Lugar', 4, 'Taller 4 Habitar y Lugar', '#dcdee0'),
('Diseño Estructural', 4, 'Diseño Estructural', '#d36e54'),
('Sistemas Reticulados', 4, 'Sistemas Reticulados', '#d36e54'),
('Modelado de Información de Construcción', 4, 'Modelado de Información de Construcción', '#b17076'),
('Seminario de Extensión 2', 4, 'Seminario de Extensión 2', '#e5bc7d'),
('Inglés General III', 4, 'Inglés General III', '#dfccc5'),
('Workshop Latitud Sur. Convalida por taller 3, 4 ó 5.', 5, 'Workshop Latitud Sur. Convalida por taller 3, 4 ó 5.', '#e5bc7d'),
('Taller 5 Multiescala', 5, 'Taller 5 Multiescala', '#dcdee0'),
('Paisaje y Territorio', 5, 'Paisaje y Territorio', '#a7b2b7'),
('Práctica del Urbanismo', 5, 'Práctica del Urbanismo', '#f4b7a5'),
('Arquitectura Contemporánea', 5, 'Arquitectura Contemporánea', '#ce8c7c'),
('Seminario de Extensión 3', 5, 'Seminario de Extensión 3', '#e5bc7d'),
('Curso de Formación General', 5, 'Curso de Formación General', '#dfccc5'),
('Taller 6 Multiescala', 6, 'Taller 6 Multiescala', '#dcdee0'),
('Workshop Europa. Convalida por taller 6, 7 u 8.', 6, 'Workshop Europa. Convalida por taller 6, 7 u 8.', '#e5bc7d'),
('Laboratorio de Aplicación Estructural', 6, 'Laboratorio de Aplicación Estructural', '#d36e54'),
('Infraestructuras de la Edificación', 6, 'Infraestructuras de la Edificación', '#d36e54'),
('Fabricación Digital', 6, 'Fabricación Digital', '#b17076'),
('Seminario de Extensión 4', 6, 'Seminario de Extensión 4', '#e5bc7d'),
('Curso de Formación General', 6, 'Curso de Formación General', '#dfccc5'),
('Workshop Europa. Convalida por taller 6, 7 u 8.', 7, 'Workshop Europa. Convalida por taller 6, 7 u 8.', '#e5bc7d'),
('Taller 7 Especialización', 7, 'Taller 7 Especialización', '#dcdee0'),
('Optativo 1 *', 7, 'Optativo 1 *', '#97979a'),
('Optativo 2 *', 7, 'Optativo 2 *', '#97979a'),
('Optativo 3 *', 7, 'Optativo 3 *', '#97979a'),
('Curso de Formación General', 7, 'Curso de Formación General', '#dfccc5'),
('Workshop Europa. Convalida por taller 6, 7 u 8.', 8, 'Workshop Europa. Convalida por taller 6, 7 u 8.', '#e5bc7d'),
('Taller 8 Especialización', 8, 'Taller 8 Especialización', '#dcdee0'),
('Optativo 4 *', 8, 'Optativo 4 *', '#97979a'),
('Optativo 5 *', 8, 'Optativo 5 *', '#97979a'),
('Optativo 6 *', 8, 'Optativo 6 *', '#97979a'),
('Curso de Formación General', 8, 'Curso de Formación General', '#dfccc5'),
('Práctica Profesional Intensiva', 9, 'Práctica Profesional Intensiva', '#dfccc5'),
('Seminario Profesional', 9, 'Seminario Profesional', '#dfccc5'),
('Seminario y Anteproyecto', 10, 'Seminario y Anteproyecto', '#dfccc5'),
('Opción Inicio Magíster de Continuidad', 10, 'Opción Inicio Magíster de Continuidad', '#e5bc7d'),
('Proyecto de Título', 11, 'Proyecto de Título', '#dfccc5'),
('Opción Inicio Magíster de Continuidad', 11, 'Opción Inicio Magíster de Continuidad', '#e5bc7d');
