INSERT INTO Ramo (nombre, year, semestre, descripcion, color) VALUES
('T1 + T2 Orden y Espacio', 1, 1, 'T1 + T2 Orden y Espacio', '#dcdee0'),
('Historia del Urbanismo', 1, 1, 'Historia del Urbanismo', '#f4b7a5'),
('Arquitectura Clásica', 1, 1, 'Arquitectura Clásica', '#ce8c7c'),
('Ciencias para la Arquitectura', 1, 1, 'Ciencias para la Arquitectura', '#d36e54'),
('Visualización y Materia', 1, 1, 'Visualización y Materia', '#b17076'),
('T1 + T2 Orden y Espacio', 1, 2, 'T1 + T2 Orden y Espacio', '#dcdee0'),
('Análisis Estructural', 1, 2, 'Análisis Estructural', '#d36e54'),
('Procesos Constructivos Macizos', 1, 2, 'Procesos Constructivos Macizos', '#d36e54'),
('Diseño Asistido por Computador', 1, 2, 'Diseño Asistido por Computador', '#b17076'),
('Inglés General I', 1, 2, 'Inglés General I', '#dfccc5'),
('Taller 3 Habitar y Lugar', 2, 1, 'Taller 3 Habitar y Lugar', '#dcdee0'),
('Workshop Latitud Sur. Convalida por taller 3, 4 ó 5.', 2, 1, 'Workshop Latitud Sur. Convalida por taller 3, 4 ó 5.', '#e5bc7d'),
('Paisaje y Lugar', 2, 1, 'Paisaje y Lugar', '#a7b2b7'),
('Teoría del Urbanismo', 2, 1, 'Teoría del Urbanismo', '#f4b7a5'),
('Arquitectura Moderna', 2, 1, 'Arquitectura Moderna', '#ce8c7c'),
('Seminario de Extensión 1', 2, 1, 'Seminario de Extensión 1', '#e5bc7d'),
('Inglés General II', 2, 1, 'Inglés General II', '#dfccc5'),
('Workshop Latitud Sur. Convalida por taller 3, 4 ó 5.', 2, 2, 'Workshop Latitud Sur. Convalida por taller 3, 4 ó 5.', '#e5bc7d'),
('Taller 4 Habitar y Lugar', 2, 2, 'Taller 4 Habitar y Lugar', '#dcdee0'),
('Diseño Estructural', 2, 2, 'Diseño Estructural', '#d36e54'),
('Sistemas Reticulados', 2, 2, 'Sistemas Reticulados', '#d36e54'),
('Modelado de Información de Construcción', 2, 2, 'Modelado de Información de Construcción', '#b17076'),
('Seminario de Extensión 2', 2, 2, 'Seminario de Extensión 2', '#e5bc7d'),
('Inglés General III', 2, 2, 'Inglés General III', '#dfccc5'),
('Workshop Latitud Sur. Convalida por taller 3, 4 ó 5.', 3, 1, 'Workshop Latitud Sur. Convalida por taller 3, 4 ó 5.', '#e5bc7d'),
('Taller 5 Multiescala', 3, 1, 'Taller 5 Multiescala', '#dcdee0'),
('Paisaje y Territorio', 3, 1, 'Paisaje y Territorio', '#a7b2b7'),
('Práctica del Urbanismo', 3, 1, 'Práctica del Urbanismo', '#f4b7a5'),
('Arquitectura Contemporánea', 3, 1, 'Arquitectura Contemporánea', '#ce8c7c'),
('Seminario de Extensión 3', 3, 1, 'Seminario de Extensión 3', '#e5bc7d'),
('Curso de Formación General', 3, 1, 'Curso de Formación General', '#dfccc5'),
('Taller 6 Multiescala', 3, 2, 'Taller 6 Multiescala', '#dcdee0'),
('Workshop Europa. Convalida por taller 6, 7 u 8.', 3, 2, 'Workshop Europa. Convalida por taller 6, 7 u 8.', '#e5bc7d'),
('Laboratorio de Aplicación Estructural', 3, 2, 'Laboratorio de Aplicación Estructural', '#d36e54'),
('Infraestructuras de la Edificación', 3, 2, 'Infraestructuras de la Edificación', '#d36e54'),
('Fabricación Digital', 3, 2, 'Fabricación Digital', '#b17076'),
('Seminario de Extensión 4', 3, 2, 'Seminario de Extensión 4', '#e5bc7d'),
('Curso de Formación General', 3, 2, 'Curso de Formación General', '#dfccc5'),
('Workshop Europa. Convalida por taller 6, 7 u 8.', 4, 1, 'Workshop Europa. Convalida por taller 6, 7 u 8.', '#e5bc7d'),
('Taller 7 Especialización', 4, 1, 'Taller 7 Especialización', '#dcdee0'),
('Optativo 1 *', 4, 1, 'Optativo 1 *', '#97979a'),
('Optativo 2 *', 4, 1, 'Optativo 2 *', '#97979a'),
('Optativo 3 *', 4, 1, 'Optativo 3 *', '#97979a'),
('Curso de Formación General', 4, 1, 'Curso de Formación General', '#dfccc5'),
('Workshop Europa. Convalida por taller 6, 7 u 8.', 4, 2, 'Workshop Europa. Convalida por taller 6, 7 u 8.', '#e5bc7d'),
('Taller 8 Especialización', 4, 2, 'Taller 8 Especialización', '#dcdee0'),
('Optativo 4 *', 4, 2, 'Optativo 4 *', '#97979a'),
('Optativo 5 *', 4, 2, 'Optativo 5 *', '#97979a'),
('Optativo 6 *', 4, 2, 'Optativo 6 *', '#97979a'),
('Curso de Formación General', 4, 2, 'Curso de Formación General', '#dfccc5'),
('Práctica Profesional Intensiva', 5, 1, 'Práctica Profesional Intensiva', '#dfccc5'),
('Seminario Profesional', 5, 1, 'Seminario Profesional', '#dfccc5'),
('Seminario y Anteproyecto', 5, 2, 'Seminario y Anteproyecto', '#dfccc5'),
('Opción Inicio Magíster de Continuidad', 5, 2, 'Opción Inicio Magíster de Continuidad', '#e5bc7d'),
('Proyecto de Título', 5, 3, 'Proyecto de Título', '#dfccc5'),
('Opción Inicio Magíster de Continuidad', 5, 3, 'Opción Inicio Magíster de Continuidad', '#e5bc7d');
